### PR TITLE
Handle aws errors that do not have a `#` in the type

### PR DESCRIPTION
**Pull request by sneako**
addresses #619 

The exception response body in the new test case, is what I have observed in production while I was trying to figure out why these failed requests were not being retried.

### CODE REVIEW

**Comment by Hinidu** [comment]
Partial duplicate of #605

**Comment by sneako** [comment]
Hey @bernardd thanks for stepping up and taking over maintenance here! I was curious if you have any thoughts or concerns about this PR. I have been maintaining a fork of ex_aws with this PR merged in for my company for over two years now 😄

**Comment by bernardd** [comment]
On inspection, I don't have any concerns, in fact. Let's get this merged and get you off your fork :)

**Comment by sneako** [comment]
Thank you @bernardd !

**Pull request merged**
