### PR TITLE
Add an additional parameter to ExAws.Auth for specifying headers.

### PR DESCRIPTION
**Pull request by archseer**
Addresses ex-aws/ex_aws_s3#36, see my comments on #540 for the rationale.

### CODE REVIEW

**Comment by jerel** [comment]
I believe this is a breaking change in the sense that if someone today is using `query_params` to pass things like `content-type` in the URLs they generate, after they upgrade S3 will cease verifying the value of the `Content-Type` header at upload time until they add it to the new `headers` option.

I think it's a good fix regardless... not sure if there'd be a way to make it fully backward compatible but I can't think of any good ways. One ugly solution might be to temporarily emit a warning if `query_params` is provided and `headers` is not.

**Comment by archSeer** [comment]
Well I mean, 540 was a breaking change as well so this is just bringing ex_aws back to where it was. Given that the URLs it generates still work, and that the original documentation never mentioned headers, I think it's fine. -- I'll add some tests later this week and document the new option, just so the documentation is a bit clearer.

**Comment by tjshipe** [comment]
Was this merged in a different PR? I found this one: https://github.com/ex-aws/ex_aws_s3/pull/39 but it's also open. I'm looking to set a `content-disposition` header to set a filename on download. I think one of these PRs would solve my issue. Is there anything I can help with to get these merged in?

**Comment by benwilson512** [comment]
Thanks, this seems like the least intrusive solution.

**Pull request merged**
