### PR TITLE
added chime support

### PR DESCRIPTION
**Pull request by marinakr**
Example:
```
   %ExAws.Operation.JSON{
          service: :chime,  
          http_method: :post,  
          path: "/meetings", 
          data: %{
             "ClientRequestToken" => "client_token_foo", 
             "ExternalMeetingId" => "test_id",
             "MediaRegion" => "us-east-2",
             "MeetingHostId" => "bar.localhost"
          }
}
|>  ExAws.request()
```
Response:
```
{:ok,
 %{
   "Meeting" => %{
     "ExternalMeetingId" => "test_id",
     "MediaPlacement" => %{
       "AudioFallbackUrl" => "wss://haxrp.m1.ue2.app.chime.aws:443/calls/11111111-9ae4-4f07-8ced-a7b0016b3339",
       "AudioHostUrl" => "c00000000e8df2fe0fd97e91dce65b04.k.m1.ue2.app.chime.aws:3478",
       "ScreenDataUrl" => "wss://bitpw.m1.ue2.app.chime.aws:443/v2/screen/11111111-9ae4-4f07-8ced-a7b0016b3339",
       "ScreenSharingUrl" => "wss://bitpw.m1.ue2.app.chime.aws:443/v2/screen/11111111-9ae4-4f07-8ced-a7b0016b3339",
       "ScreenViewingUrl" => "wss://bitpw.m1.ue2.app.chime.aws:443/ws/connect?passcode=null&viewer_uuid=null&X-BitHub-Call-Id=11111111-9ae4-4f07-8ced-a7b0016b3339",
       "SignalingUrl" => "wss://signal.m1.ue2.app.chime.aws/control/11111111-9ae4-4f07-8ced-a7b0016b3339",
       "TurnControlUrl" => "https://ccp.cp.ue1.app.chime.aws/v2/turn_sessions"
     },
     "MediaRegion" => "us-east-2",
     "MeetingId" => "11111111-9ae4-4f07-8ced-a7b0016b3339"
   }
 }}
```

### CODE REVIEW

**Comment by bernardd** [comment]
Hey @marinakr - were you intending to write an `ex_aws_chime` library to go along with this? I was just about to start doing that myself, but obviously I'd rather not duplicate work. If you are working on it, is there somewhere I can contribute? Alternatively, if I make a start on it I'd be happy for any assistance.

**Comment by marinakr** [comment]
@bernardd I am working on it - https://github.com/marinakr/ex_aws_chime/tree/develop

**Comment by bernardd** [comment]
Cool - I started mucking around myself today (though taking a much more "code first, documentation later" approach :)
I also tried to abstract out the functionality a bit rather than having the caller pass in full JSON objects. Mine's at https://github.com/circles-learning-labs/ex_aws_chime
Feel free to use whatever you like - if you don't have time to work on yours I might keep pushing on on mine for the time being and we'll see where we end up.

**Comment by bernardd** [comment]
@marinakr and anyone else looking at Chime - I've completed a first-pass implementation of an `ex_aws_chime` library over at https://github.com/circles-learning-labs/ex_aws_chime. It implements all the API actions, complete with typing. I'm still pondering the best approach for a few actions that involve search parameters and paging - I'll try to figure them out in the next couple of days, but any feedback and suggestions are welcome. It almost certainly has typos - I haven't had a chance to test even close to all of the 119 actions yet :)

@benwilson512 (or whoever else is in charge of `ex_aws`) - what's the process for getting this accepted into the official ex-aws set of libraries? I'm happy to take any feedback and make any changes required.

**Comment by bernardd** [comment]
@benwilson512 I also took the liberty of grabbing `ex_aws_chime` on hex.pm and publishing to that - more than happy to transfer that over to the official project too.

**Comment by rwperez** [comment]
@bernardd, assuming for ex_aws_chime to function you need this PR merged.
What is the status on getting this merged?

**Comment by bernardd** [comment]
> @bernardd, assuming for ex_aws_chime to function you need this PR merged.

If you want to run from the hex release, yes. Obviously you can run from @marinakr's branch until then (which is what we're doing).

**Comment by ianko** [comment]
+1 waiting the PR to be merged.

**Comment by bernardd** [comment]
I've merged a simpler version of this that just sets a global endpoint rather than the same one per region. See https://github.com/ex-aws/ex_aws/pull/719. It works fine in my testing, but if anyone knows a reason to use the longer version provided here, please let me know.

**Pull request closed without merging**
