### PR TITLE
Extend supported regions.

### PR DESCRIPTION
**Pull request by mmzx**
Please see diff.

### CODE REVIEW

**Comment by mmzx** [comment]
ping @bernardd

**Comment by jgoering** [comment]
@bernardd would it be possible to release a new version with updated region support soon? I would greatly appreciate it, since otherwise we need to go through a lengthy approval process with our security teams to switch to a fork.

Let me know if there is anything else we can help with in this regard. I think there are also others who would be interested in this, see https://github.com/ex-aws/ex_aws/pull/1050 and https://github.com/ex-aws/ex_aws/pull/1051

**Comment by bernardd** [comment]
Hi @mmzx - thanks for the PR and apologies for the delay getting to it.

**Comment by mmzx** [comment]
Thank you @bernardd!

**Comment by jgoering** [comment]
Thank you @bernardd !

**Pull request merged**
