### PR TITLE
Add support for credentials_process

### LINKED ISSUE #664: Support `credential_process` in `~/.aws/config`?
The AWS CLI [allows configuring](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html) a `credential_process` - an external command to run which returns credentials in a specified format. Eg:

```
[profile dev]
credential_process = my_command -user me -role some_role
```

In our case, we use this to periodically get a new security token, as you added support for in https://github.com/ex-aws/ex_aws/pull/144/files

Would you like a PR to support automatically and periodically running the `credential_process` command?

### PR DESCRIPTION
**Pull request by JoeyBG**
Closes #664.

I've been testing it locally for a couple weeks, since I now use 1Password to store my AWS credentials.

I did my best to add clear error messages 🙂!

Here's the relevant AWS documentation : https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html

### CODE REVIEW

**Comment by bernardd** [comment]
Hi @JoeyBG
Thanks for the PR, that all looks great. Would you be able to add some docs/examples and some tests to cover the functionality please?
Apologies for the delay getting back to you.

**Comment by JoeyBG** [comment]
Hi @bernardd,

I'll add an example sometime this week - I'm not sure I should add documentation, besides maybe a link to the official AWS doc, since it's basically going to be saying the same thing, and risk being outdated if they change how it works.

I tried adding tests before opening the PR, but I couldn't easily find a way without refactoring the whole module. There don't seem to be any tests for that part. I'll need more guidance from you to proceed.

**Comment by bernardd** [comment]
You're right - those tests are a bit of a shambles and/or missing entirely. Oh well.
In terms of documentation, just a quick example in the README of how to use this feature would be fine, just under the `AWS Key  configuration` section. Cheers.

**Comment by bernardd** [comment]
Oh wait, I see - this is a config that lives in the AWS config itself, and this just adds support for it. Okay, nevermind documenting it then :)

**Pull request merged**
